version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: "my_store_project_db"
    environment:
      POSTGRES_DB: "my_store_project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5434:5434"