spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/my_store_project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    expose-request-attributes: true
